version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-80}:80"
    environment:
      - VITE_API_BASE_URL=http://udcito-api:8000
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - VITE_APP_NAME=${APP_NAME:-Asistente UDC}
      - VITE_ORGANIZATION_NAME=${ORGANIZATION_NAME:-Universidad del Chubut}
      - VITE_LOGO_BG_COLOR=${LOGO_BG_COLOR:-#004A98}
      - VITE_LOGO_TEXT_COLOR=${LOGO_TEXT_COLOR:-#FFFFFF}
      - VITE_MOCK_ENABLED=${MOCK_ENABLED:-true}
      - VITE_DEV_TOOLS_ENABLED=${DEV_TOOLS_ENABLED:-false}
      - VITE_FEATURE_AUDIO_INPUT=${FEATURE_AUDIO_INPUT:-false}
      - VITE_FEATURE_FILE_UPLOAD=${FEATURE_FILE_UPLOAD:-false}
      - VITE_FEATURE_LIKE_BUTTON=${FEATURE_LIKE_BUTTON:-true}
      - VITE_FEATURE_DISLIKE_BUTTON=${FEATURE_DISLIKE_BUTTON:-true}
      - VITE_FEATURE_COPY_BUTTON=${FEATURE_COPY_BUTTON:-true}
    restart: unless-stopped
    networks:
      - udcito-net

networks:
  udcito-net:
    driver: bridge
    external: true
